export const START_GET_DATA = "START_GET_DATA";
export const DONE_GET_DATA = "DONE_GET_DATA";
export const MQTT_MESSAGE_ARRIVED = "MQTT_MESSAGE_ARRIVED";
export const MQTT_CONFIG = "MQTT_CONFIG";
export const MQTT_CONNECTION_SUCCESS = "MQTT_CONNECTION_SUCCESS";
export const MQTT_DISCONNECT = "MQTT_DISCONNECT";
export const MQTT_FILTER_DEVICES_NAME = "MQTT_FILTER_DEVICES_NAME";
export const DEVICES_ONLINE = "DEVICES_ONLINE";
export const DEVICES_OFFLINE = "DEVICES_OFFLINE";
export const CHECKED_ONLINE = "CHECKED_ONLINE";
export const CHECKED_OFFLINE = "CHECKED_OFFLINE";
export const LWT = "LWT";
export const POPUP_DEVICE = "POPUP_DEVICE";

// const ActionTypes = {
//   START_GET_DATA: "START_GET_DATA",
//   DONE_GET_DATA: "DONE_GET_DATA",
//   MQTT_MESSAGE_ARRIVED: "MQTT_MESSAGE_ARRIVED",
//   MQTT_CONFIG: "MQTT_CONFIG",
//   MQTT_CONNECTION_SUCCESS: "MQTT_CONNECTION_SUCCESS",
//   MQTT_DISCONNECT: "MQTT_DISCONNECT",
//   MQTT_FILTER_DEVICES_NAME: "MQTT_FILTER_DEVICES_NAME",
//   DEVICES_ONLINE: "DEVICES_ONLINE",
//   DEVICES_OFFLINE: "DEVICES_OFFLINE",
//   CHECKED_ONLINE: "CHECKED_ONLINE",
//   CHECKED_OFFLINE: "CHECKED_OFFLINE",
//   LWT: "LWT",
//   POPUP_DEVICE: "POPUP_DEVICE"
// };
// export default ActionTypes;
